// Put new content to the top of the array!
// interface Entry {
//   type: article | video | audio = article
//   url: string,
//   title?: string,
//   author?: string,
//   tags?: string[]
//   dateListed: ISO8601 (used for the RSS)
// };
const DataList = [
  {
    url: "https://contrarianthinking.co/one-billionaires-secret-to-wealth/",
    title: "One Billionaire’s Secret to Wealth: Framework for Becoming A Contrarian",
    author: "Codie Sanchez",
    dateListed: "2023-06-08T21:35:00.000Z",
  },
  {
    url: "https://www.honeycomb.io/blog/hard-stuff-nobody-talks-about-llm",
    title: "All the Hard Stuff Nobody Talks About when Building Products with LLMs",
    author: "Phillip Carter",
    dateListed: "2023-06-06T11:05:00.000Z",
  },
  {
    url: "https://www.honeycomb.io/blog/testing-in-production",
    title: "Testing in Production: Why You Should Never Stop Doing It",
    author: "Charity Majors",
    dateListed: "2023-06-06T11:00:00.000Z",
  },
  {
    url: "https://djhworld.github.io/hyperloglog/",
    title: "HyperLogLog - visual helper guide",
    author: "Daniel James Harper",
    dateListed: "2023-06-05T22:05:00.000Z",
  },
  {
    url: "https://kerkour.com/overthinking",
    title: "Overthinking",
    author: "Sylvain Kerkour",
    dateListed: "2023-06-04T14:05:00.000Z",
  },
  {
    url: "https://kerkour.com/engineer-vs-entrepreneur-mindset",
    title: "Engineer vs Entrepreneur Mindset",
    author: "Sylvain Kerkour",
    dateListed: "2023-06-04T14:00:00.000Z",
  },
  {
    url: "https://jamesclear.com/stop-procrastinating-seinfeld-strategy",
    title: "How to Stop Procrastinating on Your Goals by Using the “Seinfeld Strategy”",
    author: "James Clear",
    dateListed: "2023-05-29T17:00:00.000Z",
  },
  {
    url: "https://jamesclear.com/delayed-gratification",
    title: "40 Years of Stanford Research Found That People With This One Quality Are More Likely to Succeed",
    author: "James Clear",
    dateListed: "2023-05-29T16:00:00.000Z",
  },
  {
    url: "https://aswathdamodaran.substack.com/p/earnings-cash-flows-and-free-cash",
    title: "Earnings, Cash Flows and Free Cash Flows: A Primer",
    author: "Aswath Damodaran",
    dateListed: "2023-05-27T22:05:00.000Z",
  },
  {
    url: "https://wattenberger.com/thoughts/boo-chatbots",
    title: "Why Chatbots Are Not the Future",
    author: "Amelia Wattenberger",
    dateListed: "2023-05-23T19:05:00.000Z",
  },
  {
    url: "https://boyter.org/posts/how-to-start-go-project-2023/",
    title: "How to start a Go project in 2023",
    author: "Ben E. C. Boyter",
    dateListed: "2023-05-23T19:00:00.000Z",
  },
  {
    url: "https://longform.asmartbear.com/two-big-things",
    title: "You can have two Big Things, but not three",
    author: "Jason Cohen",
    dateListed: "2023-05-23T18:50:00.000Z",
  },
  {
    url: "https://blog.visionarycto.com/p/why-i-love-boring-tech-startups",
    title: "Why I Love Boring Tech Startups - It pays to create boring technology that everyone needs",
    author: "Matt Watson",
    dateListed: "2023-05-16T14:05:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://blog.visionarycto.com/p/my-20-year-career-is-technical-debt",
    title: "My 20 Year Career is Technical Debt or Deprecated - Deprecated should be my middle name",
    author: "Matt Watson",
    dateListed: "2023-05-16T14:00:00.000Z",
  },
  {
    url: "http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html",
    title: "Release Early, Release Often",
    author: "Eric S. Raymond",
    dateListed: "2023-05-16T13:55:00.000Z",
  },
  {
    url: "https://medium.com/@kentbeck_7670/fast-slow-in-3x-explore-expand-extract-6d4c94a7539",
    title: "Fast/Slow in 3X: Explore/Expand/Extract",
    author: "Kent Beck",
    dateListed: "2023-05-12T16:00:00.000Z",
  },
  {
    url: "https://softwareengineeringdaily.com/2019/08/28/facebook-engineering-process-with-kent-beck/",
    title: "Facebook Engineering Process with Kent Beck",
    author: "Kent Beck",
    dateListed: "2023-05-12T16:00:00.000Z",
    type: "audio",
  },
  {
    url: "https://nathanbarry.com/creator-flywheels/",
    title: "Creator Flywheels - The Operating System for Your Business",
    author: "Nathan Barry",
    dateListed: "2023-05-11T14:00:00.000Z",
  },
  {
    url: "https://jamesclear.com/saying-no",
    title: "The Ultimate Productivity Hack is Saying No",
    author: "James Clear",
    dateListed: "2023-05-08T17:15:00.000Z",
  },
  {
    url: "https://jamesclear.com/why-facts-dont-change-minds",
    title: "Why Facts Don’t Change Our Minds",
    author: "James Clear",
    dateListed: "2023-05-08T17:05:00.000Z",
  },
  {
    url: "https://jamesclear.com/goals-systems",
    title: "Forget About Setting Goals. Focus on This Instead.",
    author: "James Clear",
    dateListed: "2023-05-08T17:00:00.000Z",
  },
  {
    url: "https://longform.asmartbear.com/more-value-not-save-money",
    title: "How repositioning a product allows you to 8x its price",
    author: "Jason Cohen",
    dateListed: "2023-04-30T21:20:00.000Z",
  },
  {
    url: "https://commoncog.com/so-good-they-cant-ignore-you/",
    title: "So Good They Can't Ignore You (book summary)",
    author: "Cedric Chin",
    dateListed: "2023-04-27T12:10:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://sive.rs/balance",
    title: "How to do what you love and make good money",
    author: "Derek Sivers",
    dateListed: "2023-04-27T10:25:00.000Z",
  },
  {
    url: "https://sive.rs/career",
    title: "How to change or build your career",
    author: "Derek Sivers",
    dateListed: "2023-04-27T10:20:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=0BaDQCjqUHU",
    title: "Derek Sivers — Finding Paths Less Traveled, Taking Giant Leaps, and Picking the Right “Game of Life”",
    author: "Derek Sivers, Tim Ferriss",
    dateListed: "2023-04-25T21:40:00.000Z",
    tags: ["favourite"],
    type: "video",
  },
  {
    url: "https://kottke.org/23/01/the-enshittification-lifecycle-of-online-platforms",
    title: "The Enshittification Lifecycle of Online Platforms",
    author: "Jason Kottke",
    dateListed: "2023-04-25T16:10:00.000Z",
  },
  {
    url: "https://sive.rs/a",
    title: "Anything You Want - 40 lessons for a new kind of entrepreneur",
    author: "Derek Sivers",
    dateListed: "2023-04-24T22:45:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://bitfieldconsulting.com/golang/tao-of-go",
    title: "The Tao of Go",
    author: "John Arundel",
    dateListed: "2023-04-20T19:00:00.000Z",
  },
  {
    url: "https://liamrosen.com/fitness.html",
    title: "Beginner's Health and Fitness Guide",
    author: "Liam Rosen",
    dateListed: "2023-04-20T12:50:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://sive.rs/multiply",
    title: "Ideas are just a multiplier of execution",
    author: "Derek Sivers",
    dateListed: "2023-04-20T12:45:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.joelonsoftware.com/2001/04/21/dont-let-architecture-astronauts-scare-you/",
    title: "Don’t Let Architecture Astronauts Scare You",
    author: "Joel Spolsky",
    dateListed: "2023-04-20T12:40:00.000Z",
  },
  {
    url: "https://apenwarr.ca/log/20230415",
    title: "Systems design 2: What we hope we know",
    author: "Avery Pennarun (@apenwarr)",
    dateListed: "2023-04-17T21:20:00.000Z",
  },
  {
    url: "https://longform.asmartbear.com/problem",
    title: "Excuse me, is there a problem?",
    author: "Jason Cohen",
    dateListed: "2023-04-17T21:10:00.000Z",
  },
  {
    url: "https://blog.nelhage.com/post/efficiency-vs-resiliency/",
    title: "Efficiency trades off against resiliency",
    author: "Nelson Elhage",
    dateListed: "2023-04-17T21:00:00.000Z",
  },
  {
    url: "https://newsletter.pragmaticengineer.com/p/steve-yegge",
    title: "The Full Circle on Developer Productivity with Steve Yegge",
    author: "Steve Yegge, Gergely Orosz",
    dateListed: "2023-04-15T10:15:00.000Z",
  },
  {
    url: "https://www.ycombinator.com/library/4D-yc-s-essential-startup-advice",
    title: "YC’s Essential Startup Advice",
    author: "Geoff Ralston, Michael Seibel",
    dateListed: "2023-04-13T12:30:00.000Z",
  },
  {
    url: "https://blog.cloudflare.com/oxy-the-journey-of-graceful-restarts/",
    title: "Oxy: the journey of graceful restarts",
    author: "Chris Branch",
    dateListed: "2023-04-13T12:20:00.000Z",
  },
  {
    url: "https://blog.pragmaticengineer.com/how-to-become-a-full-time-creator/",
    title: "Becoming a Full-Time Creator as a Software Engineer: Controversial Advice",
    author: "Gergely Orosz",
    dateListed: "2023-04-07T15:35:00.000Z",
  },
  {
    url: "https://www.acquired.fm/episodes/nintendo",
    title: "Nintendo - The Complete History & Strategy of Nintendo",
    author: "Acquired Podcast",
    dateListed: "2023-04-07T13:30:00.000Z",
    type: "audio",
  },
  {
    url: "https://www.datadoghq.com/blog/engineering/computing-accurate-percentiles-with-ddsketch/",
    title: "Computing Accurate Percentiles with DDSketch",
    author: "Charles Masson",
    dateListed: "2023-03-31T12:30:00.000Z",
  },
  {
    url: "https://open.spotify.com/episode/0XHHkfNNjYap6VCkMJHb7z?si=bc06d6085721418a",
    title: "Revisiting 'The Ideal Bootstrapped Business' with Jason Cohen",
    author: "Jason Cohen, Adam Wathan, Ben Orenstein",
    dateListed: "2023-03-29T13:00:00.000Z",
    type: "audio",
  },
  {
    url: "https://playbook.samaltman.com/",
    title: "Startup Playbook",
    author: "Sam Altman, Gregory Koberger",
    dateListed: "2023-03-29T13:00:00.000Z",
  },
  {
    url: "https://blog.kowalczyk.info/article/de943f80c7924745abf9405f8c7a2c67/levelsio-and-survivorship-bias.html",
    title: "@levelsio and survivorship bias",
    author: "Krzysztof Kowalczyk",
    dateListed: "2023-03-29T12:35:00.000Z",
  },
  {
    url: "https://blog.kowalczyk.info/article/cxn3/advanced-markdown-processing-in-go.html",
    title: "Advanced markdown processing in Go",
    author: "Krzysztof Kowalczyk",
    dateListed: "2023-03-29T12:30:00.000Z",
  },
  {
    url: "https://makefiletutorial.com/",
    title: "Learn Makefiles - With the tastiest examples",
    author: "Chase Lambert",
    dateListed: "2023-03-27T20:00:00.000Z",
  },
  {
    url: "https://writings.stephenwolfram.com/2023/03/chatgpt-gets-its-wolfram-superpowers/",
    title: "ChatGPT Gets Its “Wolfram Superpowers”!",
    author: "Stephen Wolfram",
    dateListed: "2023-03-23T20:00:00.000Z",
  },
  {
    url: "https://about.sourcegraph.com/blog/cheating-is-all-you-need",
    title: "Cheating is All You Need",
    author: "Steve Yegge",
    dateListed: "2023-03-23T19:00:00.000Z",
  },
  {
    url: "https://www.honeycomb.io/blog/deploys-wrong-way-change-user-experience",
    title: "Deploys Are the ✨WRONG✨ Way to Change User Experience",
    author: "Charity Majors",
    dateListed: "2023-03-20T21:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=O8xLxNje30M&ab_channel=AmazonWebServices",
    title: "AWS re:Invent 2018: Close Loops & Opening Minds: How to Take Control of Systems, Big & Small ARC337",
    author: "Colm MacCárthaigh",
    dateListed: "2023-03-19T11:30:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://longform.asmartbear.com/predict-the-future",
    title: "Navigating the unpredictability of everything",
    author: "Jason Cohen",
    dateListed: "2023-03-12T13:20:00.000Z",
  },
  {
    url: "https://www.youtube.com/playlist?list=PLUkh9m2BorqkHJz49csCvaCXf3diCLRLl",
    title: "Valuation Undergraduate Spring 2023",
    author: "Aswath Damodaran",
    dateListed: "2023-03-11T11:00:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://apenwarr.ca/log/20201227",
    title: "Systems design explains the world: volume 1",
    author: "Avery Pennarun (@apenwarr)",
    dateListed: "2023-03-09T13:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://medium.com/@fulalas/how-bullshit-has-dominated-the-tech-industry-bc63257f2a91",
    title: "How Bullshit Has Dominated The Tech Industry",
    author: "fulalas",
    dateListed: "2023-03-07T11:40:00.000Z",
  },
  {
    url: "https://letterstoanewdeveloper.com/2023/03/06/understanding-people-matters-more-than-understanding-tech/",
    title: "Understanding People Matters More Than Understanding Tech",
    author: "Dan Moore",
    dateListed: "2023-03-07T11:00:00.000Z",
  },
  {
    url: "https://lord.io/spreadsheets/",
    title: "How to recalculate a spreadsheet",
    author: "lord.io",
    dateListed: "2023-03-06T10:00:00.000Z",
  },
  {
    url: "https://pages.gseis.ucla.edu/faculty/agre/how-to-help.html",
    title: "How to help someone use a computer.",
    author: "Phil Agre",
    dateListed: "2023-03-06T10:00:00.000Z",
  },
  {
    url: "https://sive.rs/plaintext",
    title: "Write plain text files",
    author: "Derek Sivers",
    dateListed: "2023-03-05T16:50:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://benhoyt.com/writings/the-small-web-is-beautiful/",
    title: "The small web is beautiful",
    author: "Ben Hoyt",
    dateListed: "2023-03-03T19:30:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://chr.iswong.com/essays/the-dance-of-the-bees/",
    title: "The Dance of the Bees: Finding Your Path as a Creator",
    author: "Chris Wong",
    dateListed: "2023-03-02T13:50:00.000Z",
  },
  {
    url: "https://karpathy.ai/zero-to-hero.html",
    title: "Neural Networks: Zero to Hero",
    author: "Andrej Karpathy",
    dateListed: "2023-03-02T12:00:00.000Z",
    type: "video",
    tags: ["favourite", "c-ai"],
  },
  {
    url: "https://css-tricks.com/technical-writing-for-developers/",
    title: "Technical Writing for Developers",
    author: "Eluda",
    dateListed: "2023-03-02T10:00:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://websitesetup.org/web-accessibility-checklist/",
    title: "Website Accessibility (15 Best Practices)",
    author: "Bruce Lawson",
    dateListed: "2023-03-02T09:52:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://piccalil.li/tutorial/improve-the-readability-of-the-content-on-your-website/",
    title: "Improve the readability of the content on your website",
    author: "Andy Bell",
    dateListed: "2023-03-02T09:51:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://www.nngroup.com/articles/ux-writing-study-guide/",
    title: "UX Writing: Study Guide",
    author: "Anna Kaley",
    dateListed: "2023-03-02T09:50:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://brooker.co.za/blog/2020/10/19/big-changes.html",
    title: "Getting Big Things Done",
    author: "Marc Brooker",
    dateListed: "2023-03-01T13:20:00.000Z",
  },
  {
    url: "https://blog.bullettrain.co/teams-should-be-an-mvp-feature/",
    title: "Teams should be an MVP feature!",
    author: "Andrew Culver",
    dateListed: "2023-02-27T15:55:00.000Z",
  },
  {
    url: "https://blog.chriszacharias.com/page-weight-matters",
    title: "Page Weight Matters",
    author: "Chris Zacharias",
    dateListed: "2023-02-25T21:40:00.000Z",
  },
  {
    url: "https://fasterthanli.me/articles/a-half-hour-to-learn-rust",
    title: "A half-hour to learn Rust",
    author: "Amos (@fasterthanlime)",
    dateListed: "2023-02-25T21:35:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://writings.stephenwolfram.com/2023/01/wolframalpha-as-the-way-to-bring-computational-knowledge-superpowers-to-chatgpt/",
    title: "Wolfram|Alpha as the Way to Bring Computational Knowledge Superpowers to ChatGPT",
    author: "Stephen Wolfram",
    dateListed: "2023-02-24T12:30:00.000Z",
  },
  {
    url: "https://www.focusedchaos.co/p/hearts-minds-wallets-the-simple-structure",
    title: "Hearts, Minds, Wallets: the simple structure for a successful startup pitch",
    author: "Ben Yoskovitz",
    dateListed: "2023-02-22T21:30:00.000Z",
  },
  {
    // Backup: https://twitter.com/mattschnuck/status/1579121739186872320
    url: "https://www.loom.com/share/97d678b26e2e475e94efa4d1f4ce36fb",
    title: "Motivating Your Team - Magic Questions",
    author: "Matt Mochary",
    dateListed: "2023-02-22T17:50:00.000Z",
    type: "video",
  },
  {
    url: "https://blog.asmartbear.com/slc.html",
    title: "I hate MVPs. So do your customers. Make it SLC instead.",
    author: "Jason Cohen",
    dateListed: "2023-02-22T14:25:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://lauraroeder.com/exactly-how-i-cold-emailed-my-way-to-a-life-changing-exit-and-you-can-too-165d8eaf8306",
    title: "Exactly How I Cold Emailed My Way to A Life-Changing Exit (And You Can Too)",
    author: "Laura Roeder",
    dateListed: "2023-02-22T12:10:00.000Z",
  },
  {
    url: "https://lauraroeder.com/my-top-to-bottom-system-for-running-a-7-figure-bootstrapped-business-part-time-14d4bf577d33",
    title: "My Top to Bottom System For Running a 7-Figure, Bootstrapped Business Part-Time",
    author: "Laura Roeder",
    dateListed: "2023-02-22T12:00:00.000Z",
  },
  {
    url: "https://www.allthingsdistributed.com/2021/03/happy-15th-birthday-amazon-s3.html",
    title: "Happy 15th Birthday Amazon S3 -- the service that started it all",
    author: "Werner Vogels",
    dateListed: "2023-02-16T10:08:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.allthingsdistributed.com/2021/04/s3-strong-consistency.html",
    title: "Diving Deep on S3 Consistency",
    author: "Werner Vogels",
    dateListed: "2023-02-16T10:07:00.000Z",
  },
  {
    url: "https://www.allthingsdistributed.com/2017/10/a-decade-of-dynamo.html",
    title: "A Decade of Dynamo: Powering the next wave of high-performance, internet-scale applications",
    author: "Werner Vogels",
    dateListed: "2023-02-16T10:06:00.000Z",
  },
  {
    url: "https://www.allthingsdistributed.com/2016/03/10-lessons-from-10-years-of-aws.html",
    title: "10 Lessons from 10 Years of Amazon Web Services",
    author: "Werner Vogels",
    dateListed: "2023-02-16T10:05:00.000Z",
  },
  {
    url: "https://longform.asmartbear.com/exponential-growth/",
    title: "The Elephant in the room: The myth of exponential hypergrowth",
    author: "Jason Cohen",
    dateListed: "2023-02-15T20:45:00.000Z",
  },
  {
    url: "https://writings.stephenwolfram.com/2023/02/what-is-chatgpt-doing-and-why-does-it-work/",
    title: "What Is ChatGPT Doing … and Why Does It Work?",
    author: "Stephen Wolfram",
    dateListed: "2023-02-15T14:20:00.000Z",
  },
  {
    url: "https://blog.asmartbear.com/not-disruptive.html",
    title: "Not disruptive, and proud of it",
    author: "Jason Cohen",
    dateListed: "2023-02-15T14:15:00.000Z",
  },
  {
    url: "https://twitter.com/10kdiver/status/1601996286877736962",
    title: "How Often Should We Check Stock Prices?",
    author: "10-K Diver",
    dateListed: "2023-02-15T10:25:00.000Z",
  },
  {
    url: "https://longform.asmartbear.com/moats/",
    title: "Moats: Durable competitive advantage",
    author: "Jason Cohen",
    dateListed: "2023-02-13T16:05:00.000Z",
  },
  {
    url: "https://stripe.com/gb/guides/atlas/saas-pricing",
    title: "Pricing low-touch SaaS",
    author: "Patrick McKenzie (patio11)",
    dateListed: "2023-02-13T15:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://blog.asmartbear.com/kung-fu.html",
    title: "Kung Fu - Startup strategy is like Kung Fu.",
    author: "Jason Cohen",
    dateListed: "2023-02-13T12:05:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://blog.asmartbear.com/rich-vs-king-sold-company.html",
    title: "Rich vs. King in the Real World: Why I sold my company",
    author: "Jason Cohen",
    dateListed: "2023-02-13T12:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://longform.asmartbear.com/extreme-questions/",
    title: "Extreme questions to trigger new, better ideas",
    author: "Jason Cohen",
    dateListed: "2023-02-13T11:30:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.honeycomb.io/resources/how-honeycomb-manages-incident-response",
    title: "How Honeycomb Manages Incident Response",
    author: "Fred Hebert",
    dateListed: "2023-02-13T11:10:00.000Z",
  },
  {
    url: "https://www.epsilontheory.com/narrative-and-metaverse-pt-1-the-living-word/",
    title: "Narrative and Metaverse, Pt. 1: The Living Word",
    author: "Ben Hunt",
    dateListed: "2023-02-13T11:00:00.000Z",
  },
  {
    url: "https://research.swtch.com/sample",
    title: "The Magic of Sampling, and its Limitations",
    author: "Russ Cox",
    dateListed: "2023-02-10T18:50:00.000Z",
  },
  {
    url: "https://world.hey.com/dhh/invest-in-things-that-don-t-change-6f7f19e1",
    title: "Invest in things that don't change",
    author: "David Heinemeier Hansson",
    dateListed: "2023-02-10T10:40:00.000Z",
  },
  {
    url: "https://venilnoronha.io/a-simple-state-machine-framework-in-go",
    title: "A Simple State Machine Framework in Go",
    author: "Venil Noronha",
    dateListed: "2023-02-10T09:15:00.000Z",
  },
  {
    url: "https://motherduck.com/blog/big-data-is-dead/",
    title: "Big Data Is Dead",
    author: "Jordan Tigani",
    dateListed: "2023-02-07T20:15:00.000Z",
  },
  {
    url: "https://blog.codinghorror.com/rule-of-three/",
    title: "The Rule of Three",
    author: "Jeff Atwood",
    dateListed: "2023-02-01T22:30:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.gomomento.com/blog/youre-asking-why-serverless-lets-talk",
    title: "You're asking “why serverless?” Let's talk!",
    author: "Jack Christie, Khawaja Shams",
    dateListed: "2023-02-01T13:05:00.000Z",
  },
  {
    url: "https://www.gomomento.com/blog/fighting-off-fake-serverless-bandits-with-the-true-definition-of-serverless",
    title: "Fighting off faux-serverless bandits with the true definition of serverless",
    author: "Khawaja Shams, Kirk Kirkconnell",
    dateListed: "2023-02-01T13:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/blogs/database/part-3-scaling-dynamodb-how-partitions-hot-keys-and-split-for-heat-impact-performance/",
    title: "Scaling DynamoDB: How partitions, hot keys, and split for heat impact performance (Part 3: Summary and best practices)",
    author: "Jason Hunter, Vivek Natarajan",
    dateListed: "2023-01-31T22:48:00.000Z",
  },
  {
    url: "https://nathanpeck.com/amazon-ecs-scaling-best-practices/",
    title: "Amazon ECS Scalability Best Practices",
    author: "Nathan Peck",
    dateListed: "2023-01-31T22:00:00.000Z",
  },
  {
    url: "https://bitfieldconsulting.com/golang/career",
    title: "A career ending mistake",
    author: "John Arundel",
    dateListed: "2023-01-27T15:15:00.000Z",
  },
  {
    url: "https://lethain.com/lessons-not-worth-learning/",
    title: "Lessons not worth learning.",
    author: "Will Larson",
    dateListed: "2023-01-13T13:25:00.000Z",
  },
  {
    url: "http://www.paulgraham.com/growth.html",
    title: "Startup = Growth",
    author: "Paul Graham",
    dateListed: "2023-01-13T13:21:00.000Z",
  },
  {
    url: "https://www.bvp.com/atlas/scaling-to-100-million",
    title: "Scaling to $100 Million",
    author: "Mary D'Onofrio, Ethan Ding",
    dateListed: "2023-01-13T12:44:00.000Z",
  },
  {
    url: "https://lwn.net/Articles/250967/",
    title: "What every programmer should know about memory, Part 1",
    author: "Ulrich Drepper",
    dateListed: "2023-01-13T12:12:00.000Z",
  },
  {
    url: "https://www.developermarkepear.com/blog/developer-marketing-hacker-news",
    title: "How to market your dev tool on Hacker News: Learnings from Tailscale",
    author: "Kuba Czakon",
    dateListed: "2022-12-19T18:00:00.000Z",
  },
  {
    url: "https://www.troyhunt.com/10-personal-finance-lessons-for-technology-professionals/",
    title: "10 Personal Finance Lessons for Technology Professionals",
    author: "Troy Hunt",
    dateListed: "2022-12-12T15:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=u_ktRTWMX3M",
    title: "Arnold Schwarzenegger 2018 - The speech that broke the internet - Most Inspiring ever",
    author: "Arnold Schwarzenegger",
    dateListed: "2022-12-08T14:45:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://www.artofmanliness.com/character/behavior/autofocus-the-productivity-system-that-treats-your-to-do-list-like-a-river/",
    title: "Autofocus: The Productivity System That Treats Your To-Do List Like a River",
    author: "Brett & Kate McKay",
    dateListed: "2022-12-12T14:30:00.000Z",
  },
  {
    url: "https://www.youtube.com/playlist?list=PL2yQDdvlhXf_hIzmfHCdbcXj2hS52oP9r",
    title: "AWS re:Invent 2022 (all videos)",
    author: "AWS Events",
    dateListed: "2022-12-08T14:40:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://charity.wtf/2022/08/15/live-your-best-life-with-structured-events/",
    title: "Live your best life with structured events",
    author: "Charity Majors",
    dateListed: "2022-12-06T18:10:00.000Z",
  },
  {
    url: "http://_.0xffff.me/build-database-in-2020s.html",
    title: "Building a database in the 2020s",
    author: "Ed Huang",
    dateListed: "2022-12-06T18:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/cicd-pipeline/",
    title: "My CI/CD pipeline is my release captain",
    author: "Clare Liguori",
    dateListed: "2022-12-01T19:45:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://zerodha.tech/blog/scaling-with-common-sense/",
    title: "Scaling with common sense",
    author: "Kailash Nadh",
    dateListed: "2022-12-01T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=rI8tNMsozo0",
    title: "Rails Conf 2012 Keynote: Simplicity Matters",
    author: "Rich Hickey",
    dateListed: "2022-11-29T11:05:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://headrush.typepad.com/creating_passionate_users/2005/09/you_can_outspen.html",
    title: "You can out-spend or out-teach",
    author: "Kathy Sierra (Creating Passionate Users)",
    dateListed: "2022-11-27T11:12:00.000Z",
  },
  {
    url: "https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/",
    title: "An Interactive Guide to Flexbox",
    author: "Josh W. Comeau",
    dateListed: "2022-11-22T16:48:00.000Z",
  },
  {
    url: "https://thorstenball.com/blog/2020/09/08/how-can-you-not-be-romantic-about-programming/",
    title: "How can you not be romantic about programming?",
    author: "Thorsten Ball",
    dateListed: "2022-11-22T12:45:00.000Z",
  },
  {
    url: "https://docs.aws.amazon.com/whitepapers/latest/aws-fault-isolation-boundaries/",
    title: "AWS Fault Isolation Boundaries",
    author: "AWS Whitepaper",
    dateListed: "2022-11-21T21:10:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=QoqohmccTSc",
    title: "50 Entrepreneurs share priceless advice",
    author: "Multiple founders/entrepreneurs",
    dateListed: "2022-11-13T20:30:00.000Z",
    type: "video",
  },
  {
    url: "https://simonwillison.net/2022/Nov/6/what-to-blog-about/",
    title: "What to blog about",
    author: "Simon Willison",
    dateListed: "2022-11-12T19:10:00.000Z",
  },
  {
    url: "https://brooker.co.za/blog/2022/11/08/writing.html",
    title: "Writing Is Magic",
    author: "Marc Brooker",
    dateListed: "2022-11-08T22:55:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://www.joelonsoftware.com/2004/12/15/camels-and-rubber-duckies/",
    title: "Camels and Rubber Duckies",
    author: "Joel Spolsky",
    dateListed: "2022-11-08T22:50:00.000Z",
  },
  {
    url: "https://37signals.com/why-we-choose-profit",
    title: "Why We Choose Profit at 37signals",
    author: "37signals",
    dateListed: "2022-11-08T22:44:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://m.signalvnoise.com/exponential-growth-devours-and-corrupts/",
    title: "Exponential growth devours and corrupts",
    author: "David Heinemeier Hansson - DHH",
    dateListed: "2022-11-03T13:50:00.000Z",
  },
  {
    url: "https://nira.com/basecamp-history/",
    title: "How an Anti-Growth Mentality Helped Basecamp Grow to Over 2 Million Customers",
    author: "Hiten Shah",
    dateListed: "2022-11-03T13:40:00.000Z",
  },
  {
    url: "https://www.heavybit.com/library/video/self-serve-go-to-market/",
    title: "Building Self-Serve Go-to-Market with Adam Gross",
    author: "Adam Gross",
    dateListed: "2022-10-30T19:50:00.000Z",
  },
  {
    url: "https://sive.rs/n",
    title: "Hell Yeah or No - what's worth doing",
    author: "Derek Sivers",
    dateListed: "2022-10-26T17:33:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://charity.wtf/2019/05/01/friday-deploy-freezes-are-exactly-like-murdering-puppies/",
    title: "Friday Deploy Freezes are Exactly Like Murderring Puppies",
    author: "Charity Majors",
    dateListed: "2022-10-25T13:50:00.000Z",
  },
  {
    url: "https://grugbrain.dev/",
    title: "The Grug Brained Developer - A layman's guide to thinking like the self-aware smol brained",
    author: "Carson Gross",
    dateListed: "2022-10-21T13:10:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://buffett.cnbc.com/",
    title: "Warren Buffett Archive",
    author: "Warren Buffett",
    dateListed: "2022-10-12T17:10:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://css-tricks.com/the-importance-of-career-laddering/",
    title: "The Importance of Career Laddering",
    author: "Sarah Drasner",
    dateListed: "2022-10-12T17:07:00.000Z",
  },
  {
    url: "https://laetusinpraesens.org/docs/systfail.php",
    title: "Why Systems Fail and Problems Sprout Anew - Commentary on the principles of 'Systemantics'",
    author: "Anthony Judge",
    dateListed: "2022-10-12T17:07:00.000Z",
  },
  {
    url: "https://www.patterns.dev/posts/rendering-introduction/",
    title: "Introduction to rendering patterns",
    author: "Addy Osmani, Lydia Hallie",
    dateListed: "2022-10-12T17:06:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://runnersfi.com/95-must-read-articles-of-fi/",
    title: "95 Must-Read Articles of FI (Financial Independence)",
    author: "David Ward",
    dateListed: "2022-10-12T17:05:01.000Z",
  },
  {
    url: "https://scottmeyers.blogspot.com/2013/01/effective-effective-books.html",
    title: "Effective 'Effective' Books",
    author: "Scott Meyers",
    dateListed: "2022-10-12T17:05:00.000Z",
  },
  {
    url: "https://steve-yegge.blogspot.com/2007/06/rich-programmer-food.html?m=1",
    title: "Rich Programmer Food",
    author: "Steve Yegge",
    dateListed: "2022-10-04T12:12:00.000Z",
  },
  {
    url: "https://apenwarr.ca/log/20190926",
    title: "What do executives do, anyway?",
    author: "Avery Pennarun (@apenwarr)",
    dateListed: "2022-10-03T18:59:00.000Z",
  },
  {
    url: "https://dave.cheney.net/high-performance-go-workshop/gophercon-2019.html",
    title: "High Performance Go Workshop",
    author: "Dave Cheney",
    dateListed: "2022-10-03T18:58:00.000Z",
  },
  {
    url: "https://charity.wtf/2022/09/23/the-hierarchy-is-bullshit-and-bad-for-business/",
    title: "The hierarchy is bullshit (and bad for business)",
    author: "Charity Majors",
    dateListed: "2022-10-02T16:40:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://collabfund.com/blog/the-three-sides-of-risk/",
    title: "The Three Sides of Risk",
    author: "Morgan Housel",
    dateListed: "2022-10-02T16:39:00.000Z",
  },
  {
    url: "https://eatthefinancialelephant.com/dirtbag-millionaires/",
    title: "Dirtbag Millionaires",
    author: "Chris Mamula",
    dateListed: "2022-10-02T16:38:00.000Z",
  },
  {
    url: "https://www.mrmoneymustache.com/2012/01/13/the-shockingly-simple-math-behind-early-retirement/",
    title: "The Shockingly Simple Math Behind Early Retirement",
    author: "Mr. Money Mustache",
    dateListed: "2022-10-02T16:37:00.000Z",
  },
  {
    url: "https://jakearchibald.com/2017/es-modules-in-browsers/",
    title: "ECMAScript modules in browsers",
    author: "Jake Archibald",
    dateListed: "2022-09-30T16:48:00.000Z",
  },
  {
    url: "https://jakearchibald.com/2021/cors/",
    title: "How to win at CORS",
    author: "Jake Archibald",
    dateListed: "2022-09-29T19:11:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://jakearchibald.com/2016/caching-best-practices/",
    title: "Caching best practices & max-age gotchas",
    author: "Jake Archibald",
    dateListed: "2022-09-29T19:10:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://github.com/nalgeon/sqlean",
    title: "All the missing SQLite functions",
    author: "Anton Zhiyanov (and others)",
    dateListed: "2022-09-29T16:30:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://architecturenotes.co/redis/",
    title: "Redis Explained",
    author: "Mahdi Yusuf",
    dateListed: "2022-09-29T14:58:00.000Z",
  },
  {
    url: "https://fasterthanli.me/articles/remote-development-with-rust-on-fly-io",
    title: "Remote development with Rust on fly.io",
    author: "Amos (@fasterthanlime)",
    dateListed: "2022-09-29T14:28:00.000Z",
  },
  {
    url: "https://www.cs.princeton.edu/courses/archive/spr09/cos333/beautiful.html",
    title: "A Regular Expression Matcher",
    author: "Rob Pike, Brian Kernighan",
    dateListed: "2022-09-28T13:40:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://xeiaso.net/talks/how-my-website-works",
    title: "My Blog is Hilariously Overengineered to the Point People Think it's a Static Site",
    author: "Xe Iaso (Christine Dodrill)",
    dateListed: "2022-09-28T13:35:00.000Z",
  },
  {
    url: "https://worksinprogress.substack.com/p/notes-on-progress-an-environmentalist",
    title: "Notes on Progress: An environmentalist gets lunch - Why being an effective environmentalist can often feel like being a bad one",
    author: "Hannah Ritchie",
    dateListed: "2022-09-28T13:30:00.000Z",
  },
  {
    url: "https://www.theatlantic.com/newsletters/archive/2022/09/career-ambition-advice-data/671374/",
    title: "Your Career Is Just One-Eighth of Your Life",
    author: "Derek Thompson",
    dateListed: "2022-09-28T13:29:00.000Z",
  },
  {
    url: "https://blog.pragmaticengineer.com/postmortem-best-practices/",
    title: "Incident Review and Postmortem Best Practices",
    author: "Gergely Orosz",
    dateListed: "2022-09-26T00:06:00.000Z",
  },
  {
    url: "https://sacks.substack.com/p/the-wilderness-period-61f009c769ac",
    title: "The Wilderness Period - Can Your SaaS Startup Cross the Penny Gap?",
    author: "David Sacks",
    dateListed: "2022-09-26T00:05:00.000Z",
  },
  {
    url: "https://vldb.org/pvldb/volumes/15/paper/SQLite%3A%20Past%2C%20Present%2C%20and%20Future",
    title: "SQLite: Past, Present, and Future",
    author: "Kevin P Gaffney (University of Wisconsin-Madison), Martin Prammer (University of Wisconsin - Madison), Laurence C Brasfield (SQLite devs), Richard Hipp (SQLite.org), Dan R Kennedy (Sqlite), Jignesh Patel (UW - Madison)",
    dateListed: "2022-09-26T00:04:00.000Z",
  },
  {
    url: "https://sive.rs/book/ChecklistManifesto",
    title: "The Checklist Manifesto",
    author: "Atul Gawande",
    dateListed: "2022-09-16T11:05:00.000Z",
  },
  {
    url: "https://lethain.com/present-to-executives/",
    title: "How to present to executives.",
    author: "Will Larson",
    dateListed: "2022-08-31T22:22:00.000Z",
  },
  {
    url: "https://leaddev.com/managing-managers/how-streamline-your-processes-engineering-manager",
    title: "How to streamline your processes as an engineering manager - Managing managers",
    author: "Sarah Drasner",
    dateListed: "2022-08-31T22:20:00.000Z",
  },
  {
    url: "https://howvideo.works/",
    title: "How video works",
    author: "Leandro Moreira",
    dateListed: "2022-08-30T21:55:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://37signals.com/seven-shipping-principles",
    title: "Seven Shipping Principles",
    author: "37signals",
    dateListed: "2022-08-23T13:10:00.000Z",
  },
  {
    url: "https://www.jason.af/effective-devrel-buffalo-stick/",
    title: "Turn 1 piece of dev content into 10+ — use the buffalo stick",
    author: "Jason Lengstorf",
    dateListed: "2022-08-23T11:41:00.000Z",
  },
  {
    url: "https://newsletter.pragmaticengineer.com/p/becoming-a-better-writer",
    title: "Becoming a Better Writer",
    author: "Gergely Orosz",
    dateListed: "2022-08-22T17:45:00.000Z",
    tags: ["favourite", "c-writing"],
  },
  {
    url: "https://www.heinrichhartmann.com/posts/writing/",
    title: "Writing for Engineers",
    author: "Heinrich Hartmann",
    dateListed: "2022-08-17T09:30:00.000Z",
    tags: ["favourite", "c-writing"],
  },
  {
    url: "https://www.youtube.com/watch?v=XBDfsiKDpFo",
    title: "Testing Microservices: A Sane Approach Pre-Production & In Production",
    author: "Cindy Sridharan",
    dateListed: "2022-08-15T18:20:00.000Z",
    type: "video",
  },
  {
    url: "https://www.youtube.com/watch?v=fOdtgHu_KeA",
    title: "Observability for emerging infra: Charity Majors",
    author: "Charity Majors",
    dateListed: "2022-08-14T14:30:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://www.youtube.com/watch?v=Nffzkkdq7GM&t=276s&ab_channel=TalksatGoogle",
    title: "Release Engineering Keynote | Chuck Rossi | Talks at Google",
    author: "Chuck Rossi",
    dateListed: "2022-08-14T10:20:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://engineering.fb.com/2017/08/31/web/rapid-release-at-massive-scale/",
    title: "Rapid release at massive scale",
    author: "Chuck Rossi",
    dateListed: "2022-08-14T10:19:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=-Tg48MVnBeQ&ab_channel=MicroConf",
    title: "How to Build a Startup Without Funding",
    author: "Pieter Levels (@levelsio)",
    dateListed: "2022-08-09T14:35:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://debliu.substack.com/p/avoiding-the-pitfalls-of-taking-on",
    title: "Avoiding the Pitfalls of Taking on a New Role",
    author: "Deb Liu",
    dateListed: "2022-08-02T14:11:00.000Z",
  },
  {
    url: "https://debliu.substack.com/p/make-the-first-90-days-count",
    title: "Make the First 90 Days Count - A Simple 30-60-90 Day Plan",
    author: "Deb Liu",
    dateListed: "2022-08-02T14:10:00.000Z",
  },
  {
    url: "https://cacm.acm.org/magazines/2015/4/184705-who-builds-a-house-without-drawing-blueprints/fulltext",
    title: "Who Builds a House Without Drawing Blueprints?",
    author: "Leslie Lamport",
    dateListed: "2022-08-02T09:44:00.000Z",
  },
  {
    url: "https://debliu.substack.com/p/the-bias-no-one-talks-about",
    title: "The Bias No One Talks About - How workplaces favor those who speak up, and what you can do about it",
    author: "Deb Liu",
    dateListed: "2022-08-02T09:40:00.000Z",
  },
  {
    url: "https://codeburst.io/on-writing-tech-specs-6404c9791159",
    title: "On Writing Tech Specs",
    author: "Chuck Groom",
    dateListed: "2022-07-27T12:45:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://www.joelonsoftware.com/2000/05/12/strategy-letter-i-ben-and-jerrys-vs-amazon/",
    title: "Strategy Letter I: Ben and Jerry's vs. Amazon",
    author: "Joel Spolsky",
    dateListed: "2022-07-20T14:25:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.kalzumeus.com/2010/03/20/running-a-software-business-on-5-hours-a-week/",
    title: "Running A Software Business On 5 Hours A Week",
    author: "Patrick McKenzie",
    dateListed: "2022-07-20T14:05:00.000Z",
  },
  {
    url: "https://www.kalzumeus.com/2011/07/08/business-psychology/",
    title: "How Running A Business Changes The Way You Think",
    author: "Patrick McKenzie",
    dateListed: "2022-07-20T14:04:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=8PuKwEfXZqc&ab_channel=MicroConf",
    title: "How to Build a Solo SaaS Sales Machine - Steli Efti - MicroConf 2015",
    author: "Steli Efti",
    dateListed: "2022-07-20T11:46:00.000Z",
    type: "video",
  },
  {
    url: "https://www.youtube.com/watch?v=-Tg48MVnBeQ&ab_channel=MicroConf",
    title: "Leveling Up - Patrick McKenzie (Patio11) - MicroConf 2015",
    author: "Patrick McKenzie",
    dateListed: "2022-07-20T11:45:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://copyconstruct.medium.com/distributed-tracing-weve-been-doing-it-wrong-39fc92a857df",
    title: "Distributed Tracing — we've been doing it wrong",
    author: "Cindy Sridharan",
    dateListed: "2022-07-18T22:52:00.000Z",
  },
  {
    url: "https://www.honeycomb.io/blog/so-you-want-to-build-an-observability-tool/",
    title: "So You Want To Build An Observability Tool...",
    author: "Charity Majors",
    dateListed: "2022-07-18T22:51:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=otbnC2zE2rw&list=PLwcQbu9cKWck73fERHl3HK9ToBed8LETe",
    title: "Designing the Ideal Bootstrapped Business with Jason Cohen - #microconf2013",
    author: "Jason Cohen",
    dateListed: "2022-07-18T22:50:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://staffeng.com/guides/being-visible",
    title: "Being visible",
    author: "Will Larson",
    dateListed: "2022-07-18T22:46:01.000Z",
  },
  {
    url: "https://staffeng.com/guides/staying-aligned-with-authority",
    title: "Staying aligned with authority",
    author: "Will Larson",
    dateListed: "2022-07-18T22:46:00.000Z",
  },
  {
    url: "https://staffeng.com/guides/work-on-what-matters",
    title: "Work on what matters",
    author: "Will Larson",
    dateListed: "2022-07-18T22:45:00.000Z",
  },
  {
    url: "https://microfounder.com/blog/american-micro-saas-dream",
    title: "The New American Micro-SaaS Dream",
    author: "Rauno Metsa",
    dateListed: "2022-07-05T14:40:00.000Z",
  },
  {
    url: "https://freaktakes.substack.com/p/when-do-ideas-get-easier-to-find",
    title: "When do ideas get easier to find?",
    author: "Eric Gilliam",
    dateListed: "2022-06-20T11:50:00.000Z",
  },
  {
    url: "https://jvns.ca/blog/brag-documents/",
    title: "Get your work recognized: write a brag document",
    author: "Julia Evans",
    dateListed: "2022-06-13T14:10:00.000Z",
  },
  {
    url: "https://staffeng.com/guides/finding-the-right-company",
    title: "Finding the right company",
    author: "Will Larson",
    dateListed: "2022-06-13T12:35:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://medium.com/nerd-for-tech/how-i-grew-an-engineering-productivity-tool-to-impact-thousands-of-engineers-at-amazon-and-how-28a990091207",
    title: "A Tale of Elephants - How I grew a tool to impact thousands of engineers at Amazon",
    author: "Carlos Arguelles",
    dateListed: "2022-05-29T15:03:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://medium.com/nerd-for-tech/the-day-i-lost-my-job-at-microsoft-anatomy-of-stasis-f0e2cd653e3a",
    title: "The Day I Lost my Job at Microsoft - Sometimes bad things happen so that good things can happen",
    author: "Carlos Arguelles",
    dateListed: "2022-05-29T15:02:00.000Z",
  },
  {
    url: "https://stripe.com/gb/atlas/guides/business-of-saas",
    title: "The business of SaaS",
    author: "Patrick McKenzie (Stripe)",
    dateListed: "2022-05-26T21:38:00.000Z",
  },
  {
    url: "https://www.kitchensoap.com/2012/10/25/on-being-a-senior-engineer/",
    title: "On Being A Senior Engineer",
    author: "John Allspaw",
    dateListed: "2022-05-26T21:37:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://omniti.com/seeds/your-code-may-be-elegant.html",
    title: "Your Code May Be Elegant",
    author: "Leon Fayer",
    dateListed: "2022-05-26T21:36:00.000Z",
  },
  {
    url: "https://jvns.ca/blog/senior-engineer/",
    title: "What's a senior engineer's job?",
    author: "Julia Evans",
    dateListed: "2022-05-26T21:35:00.000Z",
  },
  {
    url: "https://lethain.com/career-advice/",
    title: "Some career advice.",
    author: "Will Larson",
    dateListed: "2022-05-24T21:47:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=jwG_qR6XmDQ",
    title: "Jeff Bezos - Regret Minimization Framework",
    author: "Jeff Bezos",
    dateListed: "2022-05-24T21:30:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://signalvnoise.com/posts/1619-theres-always-time-to-launch-your-dream",
    title: "There's always time to launch your dream",
    author: "David Heinemeier Hansson",
    dateListed: "2022-05-24T21:08:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://thenewstack.io/charity-majors-recipe-for-high-performing-teams/",
    title: "Charity Majors’ Recipe for High-Performing Teams",
    author: "Charity Majors",
    dateListed: "2022-05-24T21:07:00.000Z",
  },
  {
    url: "https://thorstenball.com/blog/2022/05/17/professional-programming-the-first-10-years/",
    title: "Professional Programming: The First 10 Years",
    author: "Thorsten Ball",
    dateListed: "2022-05-24T21:06:00.000Z",
  },
  {
    url: "http://www.paulgraham.com/badeconomy.html",
    title: "Why to start a startup in a bad economy",
    author: "Paul Graham",
    dateListed: "2022-05-24T21:05:00.000Z",
  },
  {
    url: "https://www.inkandswitch.com/local-first/",
    title: "Local-first software - You own your data, in spite of the cloud",
    author: "Martin Kleppmann, Adam Wiggins, Peter van Hardenberg, Mark McGranaghan",
    dateListed: "2022-05-24T21:04:00.000Z",
  },
  {
    url: "https://ferd.ca/errors-are-constructed-not-discovered.html",
    title: "Errors are constructed, not discovered",
    author: "Fred Hebert",
    dateListed: "2022-04-21T13:20:00.000Z",
  },
  {
    url: "https://copyconstruct.medium.com/testing-in-production-the-hard-parts-3f06cefaf592",
    title: "Testing in Production: the hard parts",
    author: "Cindy Sridharan",
    dateListed: "2022-04-07T18:20:00.000Z",
  },
  {
    url: "https://lethain.com/forty-year-career/",
    title: "A forty-year career.",
    author: "Will Larson",
    dateListed: "2022-04-07T17:42:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://staffeng.com/guides/what-do-staff-engineers-actually-do",
    title: "What do Staff engineers actually do?",
    author: "Will Larson",
    dateListed: "2022-04-07T17:22:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://bitfieldconsulting.com/golang/scripting",
    title: "Scripting with Go",
    author: "John Arundel",
    dateListed: "2022-03-21T17:24:00.000Z",
  },
  {
    url: "https://danluu.com/essential-complexity/",
    title: "Against essential and accidental complexity",
    author: "Dan Luu",
    dateListed: "2022-03-16T16:42:00.000Z",
  },
  {
    url: "https://danluu.com/nothing-works/",
    title: "Why is it so hard to buy things that work well?",
    author: "Dan Luu",
    dateListed: "2022-03-16T16:41:00.000Z",
  },
  {
    url: "https://zackkanter.com/2019/03/13/what-is-amazon/",
    title: "What is Amazon?",
    author: "Zack Kanter",
    dateListed: "2022-03-14T22:39:00.000Z",
  },
  {
    url: "https://charity.wtf/2021/08/21/why-every-software-engineering-interview-should-include-ops-questions/",
    title: "Why every Software Engineering Interview should include Ops Questions",
    author: "Charity Majors",
    dateListed: "2022-03-06T21:31:00.000Z",
  },
  {
    url: "https://charity.wtf/2020/11/01/questionable-advice-the-trap-of-the-premature-senior/",
    title: "Questionable Advice: The Trap of the Premature Senior",
    author: "Charity Majors",
    dateListed: "2022-03-06T21:30:00.000Z",
  },
  {
    url: "https://danluu.com/algorithms-interviews/",
    title: "Algorithms interviews: theory vs. practice",
    author: "Dan Luu",
    dateListed: "2022-02-14T14:45:00.000Z",
  },
  {
    url: "https://stratechery.com/2022/digital-advertising-in-2022/",
    title: "Digital Advertising in 2022",
    author: "Ben Thompson",
    dateListed: "2022-02-08T23:18:00.000Z",
  },
  {
    url: "https://tympanus.net/codrops/2022/01/19/animate-anything-along-an-svg-path/",
    title: "Animate Anything Along an SVG Path",
    author: "Louis Hoebregts",
    dateListed: "2022-01-31T12:02:00.000Z",
  },
  {
    url: "https://charity.wtf/2022/01/29/how-can-you-tell-if-the-company-youre-interviewing-with-is-rotten-on-the-inside/",
    title: "How can you tell if the company you're interviewing with is rotten on the inside?",
    author: "Charity Majors",
    dateListed: "2022-01-31T00:32:00.000Z",
  },
  {
    url: "https://blog.janestreet.com/magic-trace/",
    title: "Magic-trace: Diagnosing tricky performance issues easily with Intel Processor Trace",
    author: "Tristan Hume",
    dateListed: "2022-01-31T00:30:00.000Z",
  },
  {
    url: "https://www.troyhunt.com/serverless-to-the-max-doing-big-things-for-small-dollars-with-cloudflare-workers-and-azure-functions/",
    title: "Serverless to the Max: Doing Big Things for Small Dollars with Cloudflare Workers and Azure Functions",
    author: "Troy Hunt",
    dateListed: "2022-01-24T14:30:00.000Z",
  },
  {
    url: "http://boringtechnology.club/",
    title: "Choose Boring Technology",
    author: "Dan McKinley",
    dateListed: "2022-01-24T14:29:00.000Z",
  },
  {
    url: "https://remix.run/blog/remix-vs-next",
    title: "Remix vs Next.js",
    author: "Ryan Florence",
    dateListed: "2022-01-19T13:30:00.000Z",
  },
  {
    url: "https://yougotthis.io/talks/planning-preparing-next-role/",
    title: "Planning and Preparing For Your Next Role",
    author: "Rachel Lee Nabors",
    dateListed: "2022-01-19T12:30:00.000Z",
    type: "video",
  },
  {
    url: "https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/",
    title: "What Color is Your Function?",
    author: "Bob Nystrom",
    dateListed: "2022-01-19T10:40:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://thenewstack.io/a-next-step-beyond-test-driven-development/",
    title: "A Next Step Beyond Test Driven Development (TDD + Prod = ODD)",
    author: "Charity Majors",
    dateListed: "2022-01-16T20:40:00.000Z",
  },
  {
    url: "https://research.swtch.com/npm-colors",
    title: "What NPM Should Do Today To Stop A New Colors Attack Tomorrow",
    author: "Russ Cox",
    dateListed: "2022-01-13T20:00:00.000Z",
  },
  {
    url: "https://youtu.be/LwkS82zs65g",
    title: "The official ten-year retrospective of NewSQL databases",
    author: "Andy Pavlo",
    dateListed: "2022-01-11T22:00:00.000Z",
    type: "video",
  },
  {
    url: "https://jvns.ca/blog/2016/02/10/have-high-expectations-for-computers/",
    title: "Have high expectations for your computers",
    author: "Julia Evans",
    dateListed: "2022-01-11T12:30:00.000Z",
  },
  {
    url: "https://blog.wesleyac.com/posts/consider-sqlite",
    title: "Consider SQLite",
    author: "Wesley Aptekar-Cassels",
    dateListed: "2022-01-11T12:23:00.000Z",
  },
  {
    url: "https://antonz.org/sqlite-is-not-a-toy-database/",
    title: "SQLite is not a toy database",
    author: "Anton Zhiyanov",
    dateListed: "2022-01-11T11:53:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://frankchimero.com/blog/2018/everything-easy/",
    title: "Everything Easy is Hard Again",
    author: "Frank Chimero",
    dateListed: "2022-01-10T13:41:00.000Z",
  },
  {
    url: "https://research.swtch.com/deps",
    title: "Our Software Dependency Problem",
    author: "Russ Cox",
    dateListed: "2022-01-10T13:40:00.000Z",
  },
  {
    url: "https://www.tinyverse.org/",
    title: "Lightweight is the right weight",
    author: "Tinyverse",
    dateListed: "2022-01-10T13:39:00.000Z",
  },
  {
    url: "https://danluu.com/p95-skill/",
    title: "95%-ile isn't that good",
    author: "Dan Luu",
    dateListed: "2022-01-04T09:46:00.000Z",
  },
  {
    url: "https://ottertune.com/blog/2021-databases-retrospective/",
    title: "Databases in 2021: A Year in Review",
    author: "Andy Pavlo",
    dateListed: "2022-01-04T09:44:00.000Z",
  },
  {
    url: "https://jonoscript.wordpress.com/these-things-i-believe/",
    title: "These things I believe",
    author: "Jono",
    dateListed: "2022-01-04T09:43:00.000Z",
  },
  {
    url: "https://blog.codinghorror.com/performance-is-a-feature/",
    title: "Performance is a Feature",
    author: "Jeff Atwood",
    dateListed: "2021-12-26T13:18:00.000Z",
  },
  {
    url: "https://rytisbiel.com/2021/03/06/darker-corners-of-go/",
    title: "Darker Corners of Go",
    author: "Rytis Bieliunas",
    dateListed: "2021-12-26T13:17:00.000Z",
  },
  {
    url: "https://blog.codinghorror.com/discipline-makes-strong-developers/",
    title: "Discipline Makes Strong Developers",
    author: "Jeff Atwood",
    dateListed: "2021-12-26T13:15:00.000Z",
  },
  {
    url: "https://kryogenix.org/code/browser/everyonehasjs.html",
    title: "Everyone has JavaScript, right?",
    author: "Kryogenix",
    dateListed: "2021-12-15T21:14:01.000Z",
  },
  {
    url: "https://ishadeed.com/article/defensive-css/",
    title: "Defensive CSS",
    author: "Ahmad Shadeed",
    dateListed: "2021-12-13T10:14:02.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://danluu.com/postmortem-lessons/",
    title: "Reading postmortems",
    author: "Dan Luu",
    dateListed: "2021-12-13T10:14:01.000Z",
  },
  {
    url: "https://levels.io/contact/",
    title: "Why I'm unreachable and maybe you should be too",
    author: "Pieter Levels",
    dateListed: "2021-12-13T10:14:00.000Z",
  },
  {
    url: "https://www.inc.com/jessica-stillman/nasa-napping-just-26-minutes-can-improve-job-performance-by-a-third.html",
    title: "NASA: Napping Just 26 Minutes Can Improve Job Performance by a Third",
    author: "Jessica Stillman",
    dateListed: "2021-12-03T12:50:01.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=3qHkcs3kG44",
    title: "Joe Rogan Experience #1309 - Naval Ravikant",
    author: "Joe Rogan & Naval Ravikant",
    dateListed: "2021-12-03T12:50:00.000Z",
  },
  {
    url: "https://brandur.org/nanoglyphs/027-15-minutes",
    title: "Red Rocks + 15 Minutes + K-sorted IDs",
    author: "Brandur",
    dateListed: "2021-11-20T15:25:00.000Z",
  },
  {
    url: "https://brandur.org/nanoglyphs/026-ids",
    title: "Identity Crisis: Sequence v. UUID as Primary Key",
    author: "Brandur",
    dateListed: "2021-11-20T14:25:00.000Z",
  },
  {
    url: "https://wbond.net/thoughts/building_a_high_performance_text_editor",
    title: "Building a High Performance Text Editor",
    author: "Will Bond",
    dateListed: "2021-11-09T21:00:00.000Z",
  },
  {
    url: "https://www.nayuki.io/page/designing-better-file-organization-around-tags-not-hierarchies",
    title: "Designing better file organization around tags, not hierarchies",
    author: "Nayuki",
    dateListed: "2021-11-08T09:52:00.000Z",
  },
  {
    url: "https://networkcapital.substack.com/p/the-amazon-way-of-writing",
    title: "The Amazon Way of Writing - How to write clearly and influence people",
    author: "Network Capital",
    dateListed: "2021-11-05T09:02:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://medium.com/@pat_metzdorf/living-a-startup-double-life-5e2ef6295a65",
    title: "Living a Startup Double Life - Managing your startup project while staying employed full-time",
    author: "Patrick Metzdorf",
    dateListed: "2021-10-31T15:20:00.000Z",
    type: "article",
    tags: ["favourite"],
  },
  {
    url: "https://www.youtube.com/watch?v=f4_14pZlJBs&ab_channel=YCombinator",
    title: "Before the Startup with Paul Graham (How to Start a Startup 2014: Lecture 3)",
    author: "Paul Graham",
    dateListed: "2021-10-20T14:08:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://www.fredrikholmqvist.com/posts/brooks-wirth-go/",
    title: "Brooks, Wirth and Go.",
    author: "Fredrik Holmqvist",
    dateListed: "2021-10-20T14:02:00.000Z",
  },
  {
    url: "https://www.fredrikholmqvist.com/posts/why-erlang/",
    title: "Why Erlang?",
    author: "Fredrik Holmqvist",
    dateListed: "2021-10-20T14:01:00.000Z",
  },
  {
    url: "https://www.fredrikholmqvist.com/pages/why-i-hate-frameworks.html",
    title: "Why I Hate Frameworks, Benji Smith.",
    author: "Fredrik Holmqvist",
    dateListed: "2021-10-20T14:00:00.000Z",
  },
  {
    url: "http://paulgraham.com/startupmistakes.html",
    title: "The 18 mistakes that kill startups",
    author: "Paul Graham",
    dateListed: "2021-10-19T15:21:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.ycombinator.com/library/4Q-a-minimum-viable-product-is-not-a-product-it-s-a-process",
    title: "A Minimum Viable Product Is Not a Product, It's a Process",
    author: "Jim Brikman",
    dateListed: "2021-10-19T15:20:00.000Z",
  },
  {
    url: "https://www.ycombinator.com/library/51-learning-math-for-machine-learning",
    title: "Learning Math for Machine Learning",
    author: "Vincent Chen",
    dateListed: "2021-10-18T10:47:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.joelonsoftware.com/2001/01/27/daily-builds-are-your-friend/",
    title: "Daily Builds Are Your Friend",
    author: "Joel Spolsky",
    dateListed: "2021-10-11T15:15:00.000Z",
  },
  {
    url: "https://www.joelonsoftware.com/2002/01/06/fire-and-motion/",
    title: "Fire And Motion",
    author: "Joel Spolsky",
    dateListed: "2021-10-11T15:01:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/",
    title: "Things You Should Never Do, Part I",
    author: "Joel Spolsky",
    dateListed: "2021-10-11T15:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=Jib2AmRb_rk",
    title: "SQLite: The Database at the Edge of the Network with Dr. Richard Hipp",
    author: "Richard Hipp",
    dateListed: "2021-10-08T12:25:00.000Z",
    type: "video"
  },
  {
    url: "https://thenewstack.io/rust-vs-go-why-theyre-better-together/",
    title: "Rust vs. Go: Why They’re Better Together",
    author: "Steve Francia",
    dateListed: "2021-10-04T13:20:00.000Z",
  },
  {
    url: "https://boyter.org/2018/03/collection-favorite-optimization-posts-articles/",
    title: "Collection of my favorite optimization posts and articles",
    author: "Ben E. C. Boyter",
    dateListed: "2021-09-29T11:52:00.000Z",
  },
  {
    url: "https://boyter.org/posts/abusing-aws-to-make-a-search-engine/",
    title: "Abusing AWS Lambda to make an Aussie Search Engine",
    author: "Ben E. C. Boyter",
    dateListed: "2021-09-29T09:27:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.youtube.com/watch?v=4dfk3ucthN8&ab_channel=ReactConference",
    title: "React 2014 - Responding in a Timely Manner",
    author: "Martin Thompson",
    dateListed: "2021-09-28T20:25:00.000Z",
    type: "video",
  },
  {
    url: "https://tonsky.me/blog/disenchantment/",
    title: "Software disenchantment",
    author: "Nikita Prokopov",
    dateListed: "2021-09-28T19:36:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://blog.pragmaticengineer.com/what-silicon-valley-gets-right-on-software-engineers/",
    title: "What Silicon Valley \"Gets\" about Software Engineers that Traditional Companies Do Not",
    author: "Gergely Orosz",
    dateListed: "2021-09-27T21:36:00.000Z",
  },
  {
    url: "https://noidea.dog/glue",
    title: "Technical leadership and glue work",
    author: "Tanya Reilly",
    dateListed: "2021-09-27T21:04:00.000Z",
  },
  {
    url: "https://newsletter.pragmaticengineer.com/p/project-management-in-tech",
    title: "How Big Tech Runs Tech Projects and the Curious Absence of Scrum",
    author: "Gergely Orosz",
    dateListed: "2021-09-27T21:03:00.000Z",
  },
  {
    url: "http://www.paulgraham.com/startupideas.html",
    title: "How to Get Startup Ideas",
    author: "Paul Graham",
    dateListed: "2021-09-12T11:14:00.000Z",
  },
  {
    url: "https://www.stitcher.com/show/masters-in-business/episode/ritholtzs-masters-in-business-aswath-damodaran-interview-48339457",
    title: "Ritholtz's Masters in Business: Aswath Damodaran Interview",
    author: "Barry Ritholtz & Aswath Damodaran",
    dateListed: "2021-09-01T21:53:00.000Z",
    type: "audio",
  },
  {
    url: "http://www.paulgraham.com/top.html",
    title: "The Top Idea In Your Mind",
    author: "Paul Graham",
    dateListed: "2021-08-25T12:08:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "http://www.paulgraham.com/relres.html",
    title: "Relentlessly Resourceful",
    author: "Paul Graham",
    dateListed: "2021-08-25T12:05:00.000Z",
  },
  {
    url: "https://www.expatsoftware.com/articles/guy-on-the-beach-with-a-laptop.html",
    title: "How I built a business that lets me live on the beach full time",
    author: "Jason Kester",
    dateListed: "2021-08-24T22:16:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://stripe.com/en-gb/atlas/guides/pitching",
    title: "Pitching your early stage startup",
    author: "Patrick McKenzie (Stripe)",
    dateListed: "2021-08-24T18:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.youtube.com/watch?v=T71ibcZAX3I&ab_channel=TalksatGoogle",
    title: "The Simple Path to Wealth | JL Collins | Talks at Google",
    author: "JL Collins",
    dateListed: "2021-08-23T11:43:00.000Z",
    type: "video",
  },
  {
    url: "https://sirupsen.com/adjacent-possible/",
    title: "Adjacent Possible: Model for Peeking into the Future",
    author: "Simon Hørup Eskildsen",
    dateListed: "2021-08-21T18:25:00.000Z",
  },
  {
    url: "https://www.cmyr.net/blog/gui-framework-ingredients.html",
    title: "So you want to write a GUI framework",
    author: "Colin Rofls",
    dateListed: "2021-08-19T14:29:00.000Z",
  },
  {
    url: "https://brooker.co.za/blog/2021/04/19/latency.html",
    title: "Tail Latency Might Matter More Than You Think",
    author: "Marc Brooker",
    dateListed: "2021-08-07T08:43:00.000Z",
  },
  {
    url: "https://brooker.co.za/blog/2017/12/28/mean.html",
    title: "Is the Mean Really Useless?",
    author: "Marc Brooker",
    dateListed: "2021-08-07T08:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=uH-ffKIgb38",
    title: "The Value of Stories in Business | Aswath Damodaran | Talks at Google",
    author: "Aswath Damodaran",
    dateListed: "2021-06-09T15:00:00.000Z",
    type: "video",
  },
  {
    url: "https://www.youtube.com/watch?v=PX5-XyBNi00",
    title: "Warren Buffet's Life Advice Will Change Your Future",
    author: "Warren Buffet",
    dateListed: "2021-06-04T11:00:00.000Z",
    type: "video",
  },
  {
    url: "https://www.youtube.com/watch?v=Z5chrxMuBoo",
    title: "Valuation in Four Lessons | Aswath Damodaran | Talks at Google",
    author: "Aswath Damodaran",
    dateListed: "2021-06-03T22:00:00.000Z",
    type: "video",
    tags: ["favourite"],
  },
  {
    url: "https://arachnoid.com/equities_myths/",
    title: "Equities Myths - Things you should know about investing",
    author: "Paul Lutus",
    dateListed: "2021-05-28T23:00:00.000Z",
  },
  {
    url: "https://nav.al/rich",
    title: "How to Get Rich",
    author: "Naval",
    dateListed: "2021-05-22T21:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.allencheng.com/boundaries-book-summary-henry-cloud-john-townsend/",
    title: "Boundaries Book Summary, by Henry Cloud, John Townsend",
    author: "Allen Cheng",
    dateListed: "2021-05-11T22:00:00.000Z",
  },
  {
    url: "https://cacm.acm.org/magazines/2021/5/252179-what-serverless-computing-is-and-should-become/fulltext",
    title: "What Serverless Computing Is and Should Become: The Next Phase of Cloud Computing",
    author: "Johann Schleier-Smith, Vikram Sreekanti, Anurag Khandelwal, Joao Carreira, Neeraja J. Yadwadkar, Raluca Ada Popa, Joseph E. Gonzalez, Ion Stoica, David A. Patterson",
    dateListed: "2021-05-07T18:00:00.000Z",
  },
  {
    url: "https://shinesolutions.com/2018/01/08/falsehoods-programmers-believe-about-names-with-examples/",
    title: "Falsehoods Programmers Believe About Names – With Examples",
    author: "Tony Rogers (shine solutions group)",
    dateListed: "2021-04-30T10:00:00.000Z",
  },
  {
    url: "https://kk.org/thetechnium/1000-true-fans/",
    title: "1,000 True Fans",
    author: "Kevin Kelly",
    dateListed: "2021-04-27T23:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://kk.org/thetechnium/99-additional-bits-of-unsolicited-advice/",
    title: "99 Additional Bits of Unsolicited Advice",
    author: "Kevin Kelly",
    dateListed: "2021-04-26T21:00:00.000Z",
  },
  {
    url: "https://kk.org/thetechnium/68-bits-of-unsolicited-advice/",
    title: "68 Bits of Unsolicited Advice",
    author: "Kevin Kelly",
    dateListed: "2021-04-26T13:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://m.signalvnoise.com/reconsider/",
    title: "RECONSIDER",
    author: "David Heinemeier Hansson - DHH",
    dateListed: "2021-04-23T11:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://blog.burntsushi.net/transducers/",
    title: "Index 1,600,000,000 Keys with Automata and Rust (fst)",
    author: "Andrew Gallant",
    dateListed: "2021-04-18T21:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://gregoryszorc.com/blog/2021/04/13/rust-is-for-professionals/",
    title: "Rust is for Professionals",
    author: "Gregory Szorc",
    dateListed: "2021-04-14T12:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://www.economicliberties.us/our-work/new-money-trust/",
    title: "The New Money Trust: How Large Money Managers Control Our Economy and What We Can Do About It",
    author: "Graham Steele",
    dateListed: "2021-04-05T23:00:00.000Z",
  },
  {
    url: "https://www.bankeronwheels.com/how-to-take-advantage-of-a-recession/",
    title: "Epic Stock Market Crashes - Guide on how to take advantage of the next recession",
    author: "Raph Antoine aka Banker on Wheels",
    dateListed: "2021-04-04T22:00:00.000Z",
  },
  {
    url: "https://martin.baillie.id/wrote/gotchas-in-the-go-network-packages-defaults/",
    title: "Gotchas in the Go Network Packages Defaults",
    author: "Martin Baillie",
    dateListed: "2021-03-29T23:00:00.000Z",
  },
  {
    url: "https://golang.org/doc/effective_go",
    title: "Effective Go",
    author: "Go Team",
    dateListed: "2021-03-29T23:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
    title: "Timeouts, retries, and backoff with jitter",
    author: "Marc Brooker",
    tags: ["favourite"],
    dateListed: "2021-03-21T15:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/",
    title: "Using load shedding to avoid overload",
    author: "David Yanacek",
    tags: ["favourite"],
    dateListed: "2021-03-21T15:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=5zXAHh5tJqQ",
    title: "GopherCon 2018: Rethinking Classical Concurrency Patterns",
    author: "Bryan C. Mills",
    type: "video",
    dateListed: "2021-03-19T19:00:00.000Z",
  },
  {
    url: "https://encore.dev/blog/advanced-go-concurrency",
    title: "Advanced Go Concurrency",
    author: "André Eriksson",
    dateListed: "2021-03-19T16:00:00.000Z",
  },
  {
    url: "https://open.spotify.com/episode/0jU0dAZORvCB9zbTBz4keH?si=aniMpCV_SPyd-iRfM56voQ",
    title: "Amazon Narratives: Memos, Working Backwards from Release, More (a16z Podcast)",
    author: "Colin Bryar, Bill Carr, Sonal Chokshi",
    type: "audio",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://bost.ocks.org/mike/algorithms/",
    title: "Visualizing Algorithms",
    author: "Mike Bostock",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://world.hey.com/jason/remote-work-is-not-local-work-at-a-distance-94602802",
    title: "Remote work is not local work at a distance",
    author: "Jason Fried",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://web.dev/streams/",
    title: "Streams—The definitive guide",
    author: "Thomas Steiner",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/reliability-and-constant-work/",
    title: "Reliability, constant work, and a good cup of coffee",
    author: "Colm MacCárthaigh",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=Mj5P47F6nJg",
    title: "Structured concurrency (Kotlin)",
    author: "Roman Elizarov",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=M85UvH0TRPc",
    title: "The Internet's Own Boy: The Story of Aaron Swartz",
    author: "Brian Knappenberger - Luminant Media",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.theatlantic.com/technology/archive/2017/09/saving-the-world-from-code/540393/",
    title: "The Coming Software Apocalypse",
    author: "James Somers",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://physiqonomics.com/fat-loss/",
    title: "The Best Fat Loss Article on the Motherfuckin’ Internet",
    author: "Aadam",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.hillelwayne.com/post/crossover-project/are-we-really-engineers/",
    title: "ARE WE REALLY ENGINEERS?",
    author: "Hillel Wayne",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://play.kotlinlang.org/byExample/overview",
    title: "Learn Kotlin by Example",
    author: "JetBrains",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://jvns.ca/blog/things-your-manager-might-not-know/",
    title: "Things your manager might not know",
    author: "Julia Evans",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/automating-safe-hands-off-deployments/",
    title: "Automating safe, hands-off deployments",
    author: "Clare Liguori",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/workload-isolation-using-shuffle-sharding/",
    title: "Workload isolation using shuffle-sharding",
    author: "Colm MacCárthaigh",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://jvns.ca/blog/2021/01/04/docker-compose-is-nice/",
    title: "Docker Compose: a nice way to set up a dev environment",
    author: "Julia Evans",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://docs.google.com/document/d/199PqyG3UsyXlwieHaqbGiWVa8eMWi8zzAn0YfcApr8Q/view",
    title: "My Philosophy on Alerting (SRE)",
    author: "Rob Ewaschuk",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://medium.com/@mrabkin/the-art-of-the-awkward-1-1-f4e1dcbd1c5c",
    title: "The Art of the Awkward 1:1",
    author: "Mark Rabkin",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://nickcraver.com/blog/2016/02/03/stack-overflow-a-technical-deconstruction/",
    title: "Stack Overflow: A Technical Deconstruction",
    author: "Nick Craver",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://blog.samaltman.com/the-days-are-long-but-the-decades-are-short",
    title: "The days are long but the decades are short",
    author: "Sam Altman",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=C27RVio2rOs",
    title: "Building Product",
    author: "Michael Seibel",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "http://paulgraham.com/avg.html",
    title: "Beating the Averages",
    author: "Paul Graham",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "http://paulgraham.com/ds.html",
    title: "Do things that don't scale",
    author: "Paul Graham",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.mixcloud.com/TheJoeRoganExperience/1342-john-carmack/",
    title: "Joe Rogan Experience #1342 - John Carmack",
    author: "Joe Rogan, John Carmack",
    type: "audio",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://dave.cheney.net/2020/02/23/the-zen-of-go",
    title: "The Zen of Go",
    author: "Dave Cheney",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://crawshaw.io/blog/one-process-programming-notes",
    title: "One process programming notes (with Go and SQLite)",
    author: "David Crawshaw",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "http://www.paulgraham.com/makersschedule.html",
    title: "Maker's Schedule, Manager's Schedule",
    author: "Paul Graham",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://ivoanjo.me/blog/2018/04/08/my-thoughts-on-and-how-i-approach-code-reviews/",
    title: "my thoughts on, and how i approach code reviews",
    author: "Ivo Anjo",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://about.gitlab.com/company/culture/all-remote/asynchronous/",
    title: "Embracing asynchronous communication",
    author: "Gitlab",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.kalzumeus.com/2014/04/03/fantasy-tarsnap/",
    title: "What I Would Do If I Ran Tarsnap",
    author: "Patrick McKenzie",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.lastweekinaws.com/blog/multi-cloud-is-the-worst-practice/",
    title: "Multi-Cloud is the Worst Practice",
    author: "Corey Quinn",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://m.signalvnoise.com/why-we-choose-profit/",
    title: "Why we choose profit",
    author: "Jason Fried",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.zainrizvi.io/blog/the-impostors-advantage/",
    title: "How I learned to turn Impostor Syndrome into an Advantage - The Impostor's Advantage",
    author: "Zain Rizvi",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://aws.amazon.com/builders-library/avoiding-overload-in-distributed-systems-by-putting-the-smaller-service-in-control/",
    title: "Avoiding overload in distributed systems by putting the smaller service in control",
    author: "Joe Magerramov",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://vicki.substack.com/p/google-drive-is-production",
    title: "Google Drive is production - Look at me, I'm the source of truth now",
    author: "Vicki Boykis",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://ferd.ca/ten-years-of-erlang.html",
    title: "Ten Years of Erlang",
    author: "Fred Hebert",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://ferd.ca/awk-in-20-minutes.html",
    title: "Awk in 20 Minutes",
    author: "Fred Hebert",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=vnEf8z1aZns",
    title: "Eye Opening Speeches (compilation)",
    author: "Denzel Washington",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.newyorker.com/magazine/2018/12/10/the-friendship-that-made-google-huge",
    title: "The Friendship That Made Google Huge",
    author: "James Somers",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=RqubKSF3wig",
    title: "SQLite and Go",
    author: "David Crawshaw",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://addyosmani.com/blog/profiling-react-js/",
    title: "Profiling React.js Performance",
    author: "Addy Osmani",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=lJ8ydIuPFeU",
    title: "How NOT to Measure Latency",
    author: "Gil Tene",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/",
    title: "How to write the perfect pull request",
    author: "Keavy McMinn",
    dateListed: "2021-03-14T11:00:00.000Z",
    tags: ["c-writing"],
  },
  {
    url: "https://css-tricks.com/the-art-of-comments/",
    title: "The Art of Comments",
    author: "Sarah Drasner",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.philipotoole.com/what-i-learned-from-programming-a-database/",
    title: "WHAT I LEARNED FROM PROGRAMMING DATABASES",
    author: "Philip O'Toole",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=Unzc731iCUY",
    title: "MIT: How To Speak",
    author: "Patrick Winston",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=gdSlcxxYAA8",
    title: "The Art of Code",
    author: "Dylan Beattie",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://waitbutwhy.com/2015/12/the-tail-end.html",
    title: "The Tail End",
    author: "Tim Urban",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://howhttps.works/",
    title: "HOW HTTPS WORKS",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://aashni.me/blog/hype-yourself-youre-worth-it/",
    title: "Hype Yourself! You're Worth It!",
    author: "Aashni Shah",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.linkedin.com/pulse/toxic-work-culture-forcing-high-performing-people-quit-tim-denning/",
    title: "A Toxic Work Culture Is Forcing High-Performing People to Quit",
    author: "Tim Denning",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=JvBT4XBdoUE",
    title: "GOTO 2019 • The Soul of Erlang and Elixir",
    author: "Saša Jurić",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://brooker.co.za/blog/2019/04/03/learning.html",
    title: "Learning to build distributed systems",
    author: "Marc Brooker",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://medium.com/@paularmstrong/twitter-lite-and-high-performance-react-progressive-web-apps-at-scale-d28a00e780a3",
    title: "Twitter Lite and High Performance React Progressive Web Apps at Scale",
    author: "Paul Armstrong",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://medium.com/s/company-culture/your-companys-culture-is-who-you-hire-fire-and-promote-c69f84902983",
    title: "Your Company Culture is Who You Hire, Fire, and Promote",
    author: "Cameron Sepah",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=kGlVcSMgtV4",
    title: "Simple Made Easy",
    author: "Rich Hickey",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=YR5WdGrpoug",
    title: "Maybe Not",
    author: "Rich Hickey",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://danluu.com/startup-tradeoffs/",
    title: "Big companies v. startups",
    author: "Dan Luu",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.kalzumeus.com/2012/01/23/salary-negotiation/",
    title: "Salary Negotiation: Make More Money, Be More Valued",
    author: "Patrick McKenzie",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.kalzumeus.com/2011/10/28/dont-call-yourself-a-programmer/",
    title: "Don't Call Yourself A Programmer, And Other Career Advice",
    author: "Patrick McKenzie",
    dateListed: "2021-03-14T11:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://mcfunley.com/choose-boring-technology",
    title: "Choose Boring Technology",
    author: "Dan McKinley",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://v8.dev/blog/cost-of-javascript-2019",
    title: "The Cost Of JavaScript In 2019",
    author: "Addy Osmani",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4",
    title: "The Cost Of JavaScript In 2018",
    author: "Addy Osmani",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html",
    title: "The Clean Architecture",
    author: "Robert C. Martin (Uncle Bob)",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=pO4_Wlq8JeI",
    title: "Solid Ground",
    author: "Saša Jurić",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=7lmCu8wz8ro",
    title: "What Does It Take To Be An Expert At Python?",
    author: "James Powell",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://peter.bourgon.org/go-for-industrial-programming/",
    title: "Go for Industrial Programming",
    author: "Peter Bourgon",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://zachholman.com/talk/utc-is-enough-for-everyone-right",
    title: "UTC is enough for everyone ...right?",
    author: "Zach Holman",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://jack-vanlightly.com/blog/2017/12/4/rabbitmq-vs-kafka-part-1-messaging-topologies",
    title: "RabbitMQ vs Kafka Part 1 - Two Different Takes on Messaging",
    author: "Jack Vanlighty",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=lKXe3HUG2l4",
    title: "The Mess We're In",
    author: "Joe Armstrong",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://practicaltypography.com/why-racket-why-lisp.html",
    title: "WHY RACKET? WHY LISP?",
    author: "Matthew Butterick",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://tomjoro.github.io/2017-01-31-world-changed/",
    title: "Elixir - Erlang didn't change, the world did",
    author: "Thomas O'Rourke",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://martin.kleppmann.com/2011/03/07/accounting-for-computer-scientists.html",
    title: "Accounting for Computer Scientists",
    author: "Martin Kleppmann",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying",
    title: "The Log: What every software engineer should know about real-time data's unifying abstraction",
    author: "Jay Kreps",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://blog.acolyer.org/2017/08/22/javascript-for-extending-low-latency-in-memory-key-value-stores/",
    title: "JavaScript for extending low-latency in-memory key-value stores",
    author: "Adrian Colyer",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=_Pwlvy3zz9M",
    title: "Hitchhiker's Tour of the BEAM",
    author: "Robert Virding",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=5Zg-C8AAIGg",
    title: "The beauty of data visualization (TED-ed)",
    author: "David McCandless",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=uBjoTxosSys",
    title: "Go Tooling in Action",
    author: "Francesc Campoy",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://techcrunch.com/2017/05/14/why-amazon-is-eating-the-world/",
    title: "Why Amazon is eating the world",
    author: "Zack Kanter",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://vimeo.com/97349221",
    title: "Better Software—No Matter What: The Most Important Design Guideline",
    author: "Scott Meyers",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=itKFrXghGuA",
    title: "Computing: The first 100 years (Full Stack Fest 2016)",
    author: "Joe Armstrong",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=YaUPdgtUYko",
    title: "Stanford Seminar - Faults, Scaling, and Erlang Concurrency",
    author: "Joe Armstrong",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=CBYhVcO4WgI&list=PL5q_lef6zVkaTY_cT1k7qFNF2TidHCe-1",
    title: "Lecture 1 - How to Start a Startup",
    author: "Sam Altman, Dustin Moskovitz",
    type: "video",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#---0-78.c41sptspc",
    title: "How it feels to learn JavaScript in 2016",
    author: "Jose Aguinaga",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://fsharpforfunandprofit.com/posts/ten-reasons-not-to-use-a-functional-programming-language/",
    title: "Ten reasons not to use a statically typed functional programming language",
    author: "Scott Wlaschin",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://blog.codinghorror.com/recommended-reading-for-developers/",
    title: "Recommended Reading for Developers",
    author: "Jeff Atwood",
    tags: ["favourite"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.davidhaney.io/npm-left-pad-have-we-forgotten-how-to-program/",
    title: "NPM & left-pad: Have We Forgotten How To Program?",
    author: "David Haney",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html",
    title: "Just Say No to More End-to-End Tests",
    author: "Mike Wacker",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=PAAkCSZUG1c",
    title: "Go Proverbs",
    author: "Rob Pike",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.smashingmagazine.com/2015/10/space-yourself/",
    title: "Space Yourself",
    author: "Marcin Wichary",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://markmanson.net/not-giving-a-fuck",
    title: "The Subtle Art of Not Giving a Fuck",
    author: "Mark Manson",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "http://norvig.com/21-days.html",
    title: "Teach Yourself Programming in Ten Years",
    author: "Peter Norvig",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/",
    title: "WHAT IS CODE?",
    author: "Paul Ford",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown",
    title: "Breaking down Amazon’s mega dropdown",
    author: "Ben Kamens",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.the-paper-trail.org/post/2014-08-09-distributed-systems-theory-for-the-distributed-systems-engineer/",
    title: "Distributed systems theory for the distributed systems engineer",
    author: "Henry Robinson",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/lecture-videos/",
    title: "MIT: Introduction to Algorithms",
    author: "Prof. Erik Demaine, Prof. Srini Devadas",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://martinfowler.com/articles/continuousIntegration.html",
    title: "Continuous Integration",
    author: "Martin Fowler",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://www.youtube.com/watch?v=HHjgK6p4nrw",
    title: "The Top 10 Mistakes of Entrepreneurs",
    author: "Guy Kawasaki",
    type: "video",
    dateListed: "2021-03-14T11:00:00.000Z",
    tags: ["favourite"],
  },
  {
    url: "https://medium.com/always-be-coding/abc-always-be-coding-d5f8051afce2",
    title: "ABC: Always Be Coding - How to Land an Engineering Job",
    author: "David Byttow",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://highlyscalable.wordpress.com/2012/02/01/mapreduce-patterns/",
    title: "MAPREDUCE PATTERNS, ALGORITHMS, AND USE CASES",
    author: "Ilya Katsov",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "http://matt.might.net/articles/phd-school-in-pictures/",
    title: "The illustrated guide to a Ph.D.",
    author: "Matt Might",
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    url: "https://sealedabstract.com/rants/why-mobile-web-apps-are-slow/",
    title: "Why mobile web apps are slow",
    author: "Drew Crawford",
    tags: ["software"],
    dateListed: "2021-03-14T11:00:00.000Z",
  },
  {
    title: "Things Every Programmer Should Know",
    url: "https://www.javacodegeeks.com/2010/12/things-every-programmer-should-know.html",
    author: "Byron Kiourtzoglou",
    tags: ["software"],
    dateListed: "2021-03-14T11:00:00.000Z",
  }
];

function getHostname(urlStr) {
  try {
    return new URL(urlStr).hostname;
  } catch (e) {
    // IE,
    return "";
  }
}

function getItemId({ url, title, author }) {
  const hostname = getHostname(url);
  return `${encodeURIComponent(hostname)}-${encodeURIComponent(title)}-${encodeURIComponent(author)}`.toLowerCase();
}

module.exports = {
  getHostname,
  getItemId,
  DataList
};
